[backend]
export_port = 8080

[backend.mysql]
host = "61.139.65.141"
port = 10390
dbname = "libraryms_db"
user = "root"
password = "123456"

[backend.logger]
log_level = "trace" #trace,debug,info,warn,error
enable_file_output = false
output_directory = "log/"
output_filename = "libraryms.log"